/**
 * Homework 4, Syntactical Parser
 * Travis Libre
 * Completed 11/10/2022
 * Code originated from sample provided in class
 */

#include <stdio.h>
#include <ctype.h>
#include <string.h>

/* Character classes */
#define LETTER 0
#define DIGIT 1
#define UNKNOWN 99

/* Token codes */
#define INT_LIT 10
#define IDENT 11
#define ASSIGN_OP 20
#define ADD_OP 21
#define SUB_OP 22
#define MULT_OP 23
#define DIV_OP 24
#define LEFT_PAREN 25
#define RIGHT_PAREN 26
#define LESSER_OP 27
#define GREATER_OP 28
#define EQUAL_OP 29
#define NEQUAL_OP 30
#define LEQUAL_OP 31
#define GEQUAL_OP 32
#define SEMICOLON 33
#define MOD_OP 34
#define LEFT_CBRACE 35
#define RIGHT_CBRACE 36

/* Keyword codes */
#define KEY_READ 37
#define KEY_PRINT 38
#define KEY_WHILE 39
#define KEY_DO 40

int globalError = 0;
int globalInsideDoWhile = 0;

int lex(); // Lexeme function

/* Global Variable */
int nextToken; // Represents look-ahead

/* Local Variables */
static int charClass;
static char lexeme[100];
static char nextChar;
static int lexLen;
static FILE *in_fp;

/* Local Function declarations */
static int lookup(char ch);

static void addChar();

static void getChar();

static void getNonBlank();

void printAnswer();

static void error();

void condition();

void formCheck();

void expr();

void term();

void factor();

void formCheck() {
    if (nextToken == LEFT_PAREN) {
        lex();
        if (nextToken == IDENT) {
            lex();
            if (nextToken == RIGHT_PAREN) {
                lex();
            } else
                error();
        } else
            error();
    } else
        error();
}

void statement() {
    //printf("Enter <statement>\n");
    if (nextToken == IDENT) {
        lex();
        if (nextToken == ASSIGN_OP) {
            lex();
            expr();
        } else {
            error();
        }
    } else if (nextToken == KEY_READ) {
        lex();
        formCheck();
    } else if (nextToken == KEY_PRINT) {
        lex();
        formCheck();
    } else if (nextToken == KEY_DO) {
        lex();
        if (nextToken == LEFT_CBRACE) {
            lex();
            globalInsideDoWhile++;
            statement();
            globalInsideDoWhile--;
            if (nextToken == RIGHT_CBRACE) {
                lex();
                if (nextToken == KEY_WHILE) {
                    lex();
                    condition();
                } else error();
            } else error();
        } else error();
    } else {
        //printf("Statement error");
        error();
    }
    if (nextToken == SEMICOLON) {
        lex();
        statement();
    }
    //printf("Exit <stmt>\n");
}

void condition() {
    //printf("Enter <cond>");
    expr();
    if (nextToken == LEQUAL_OP || nextToken == GEQUAL_OP || nextToken == EQUAL_OP ||
        nextToken == NEQUAL_OP || nextToken == GREATER_OP || nextToken == LESSER_OP) {
        lex();
        expr();
    } else error();
    //printf("Exit <cond>");
}

/* expr
 * Parses strings in the language generated by the rule:
 * <expr> -> <term> {(+ | -) <term>}
 */
void expr() {
    //printf("Enter <expr>\n");

    /* Parse the first term */
    term();

    /* As long as the next token is + or -, get
    the next token and parse the next term */
    while (nextToken == ADD_OP || nextToken == SUB_OP) {
        lex();
        term();
    }


    //printf("Exit <expr>\n");
} /* End of function expr */

/* term
 * Parses strings in the language generated by the rule:
 * <term> -> <factor> {(* | /) <factor>)
 */
void term() {
    //printf("Enter <term>\n");
    /* Parse the first factor */
    factor();
    /* As long as the next token is * or /, get the
    next token and parse the next factor */
    while (nextToken == MULT_OP || nextToken == DIV_OP || nextToken == MOD_OP) {
        lex();
        factor();
    }
    //printf("Exit <term>\n");
} /* End of function term */

/* factor
 * Parses strings in the language generated by the rule:
 * <factor> -> id | int_constant | ( <expr )
 * */
void factor() {
    //printf("Enter <factor>\n");
    /* Determine which RHS */
    if (nextToken == IDENT || nextToken == INT_LIT) {
        lex(); /* Get the next token */
    } else {
        /* If the RHS is (<expr>), call lex to pass over the
        left parenthesis, call expr, and check for the right
        parenthesis */
        if (nextToken == LEFT_PAREN) {
            lex();
            expr();

            if (nextToken == RIGHT_PAREN) {
                lex();
            } else {
                error();
            }
        } /* End of if (nextToken == ... */
            /* It was not an id, an integer literal, or a left parenthesis */
        else {
            error();
        }
    } /* End of else */
    //printf("Exit <factor>\n");;
} /* End of function factor */

static void error() {
    if (globalError==0){
        printf("Error Encounter: The next lexeme was ");
        printAnswer();
    }
    globalError++;
}

/******************************************************/
/* main driver */
int main(int argc, char *argv[]) {
    printf("DanC Parser :: R11702155\n");
    if(argv[1]==NULL){
        printf("No file provided\n");
        return 2;
    }
    /* Open the input data file and process its contents */
    else if ((in_fp = fopen(argv[1], "r")) == NULL) {
        printf("ERROR - cannot open front.in \n");
        return 3;
    }
    else {
        getChar();
        do {
            lex();
            //printf("%d\n",nextToken);
            statement();
        } while (nextToken != EOF);
    }
    //printf("%d Errors.", globalError);
    if(globalError==0){
        printf("Syntax Validated\n");
        return 0;
    }
    else if(globalError>0){
        return 1;
    }
    return 0;
}

/*****************************************************/


/*****************************************************/
/* addChar - a function to add nextChar to lexeme */
static void addChar() {
    if (lexLen <= 98) {
        lexeme[lexLen++] = nextChar;
        lexeme[lexLen] = 0;
        getChar(); // Added getChar() in order to simply code, reduce repetition
    } else {
        printf("Error - lexeme is too long \n");
    }
}

/*****************************************************/
/* getChar - a function to get the next character of input and determine its
 * character class */
static void getChar() {
    if ((nextChar = getc(in_fp)) != EOF) {
        if (isalpha(nextChar))
            charClass = LETTER;
        else if (isdigit(nextChar))
            charClass = DIGIT;
        else charClass = UNKNOWN;
    } else {
        charClass = EOF;
    }
}

/*****************************************************/
/* getNonBlank - a function to call getChar until it returns a non-whitespace
 * character */
static void getNonBlank() {
    while (isspace(nextChar)) getChar();
}

/*****************************************************/


/*****************************************************/
/* lex - a simple lexical analyzer for arithmetic expressions */
int lex() {
    lexLen = 0;
    getNonBlank();

    switch (charClass) {
        /* Parse identifiers */
        case LETTER:
            addChar();
            while (charClass == LETTER || charClass == DIGIT) {
                addChar();
            }
            // Added strcmp statements to find keywords during IDENT identifier loop
            if (strcmp(lexeme, "read") == 0) {
                nextToken = KEY_READ;
            } else if (strcmp(lexeme, "print") == 0) {
                nextToken = KEY_PRINT;
            } else if (strcmp(lexeme, "while") == 0) {
                nextToken = KEY_WHILE;
            } else if (strcmp(lexeme, "do") == 0) {
                nextToken = KEY_DO;
            } else {
                nextToken = IDENT;
            }
            break;

            /* Parse integer literals */
        case DIGIT:
            addChar();
            while (charClass == DIGIT) {
                addChar();
            }
            nextToken = INT_LIT;
            break;

            /* Parentheses and operators */
        case UNKNOWN:
            lookup(nextChar);
            break;

            /* EOF */
        case EOF:
            nextToken = EOF;
            lexeme[0] = 'E';
            lexeme[1] = 'O';
            lexeme[2] = 'F';
            lexeme[3] = 0;
            break;
    } /* End of switch */
    //if (nextToken != EOF) // Answer does not show EOF tokens
    //    printAnswer();
    return nextToken;
} /* End of function lex */
/* lookup - a function to lookup operators and parentheses and return the
 * token
 * !!!
 * Added additional functionality for the multi-character lexemes
 * */
static int lookup(char ch) {
    switch (ch) {
        case '(':
            addChar();
            nextToken = LEFT_PAREN;
            break;
        case ')':
            addChar();
            nextToken = RIGHT_PAREN;
            break;
        case '+':
            addChar();
            nextToken = ADD_OP;
            break;
        case '-':
            addChar();
            nextToken = SUB_OP;
            break;
        case '*':
            addChar();
            nextToken = MULT_OP;
            break;
        case '/':
            addChar();
            nextToken = DIV_OP;
            break;
        case '<':
            addChar();
            if (nextChar == '=') { // Checks if lookahead character is the required next character for the lexeme
                // If so, add to lexeme
                addChar();
                nextToken = LEQUAL_OP;
                break;
            } else if (nextChar == '>') {
                addChar();
                nextToken = NEQUAL_OP;
                break;
            } else {
                //Else, initial character is the lexeme
                nextToken = LESSER_OP;
                break;
            }
        case '>':
            addChar();
            if (nextChar == '=') {
                addChar();
                nextToken = GEQUAL_OP;
                break;
            } else {
                nextToken = GREATER_OP;
                break;
            }
        case '=':
            addChar();
            if (nextChar == '=') {
                addChar();
                nextToken = EQUAL_OP;
                break;
            } else {
                nextToken = ASSIGN_OP;
                break;
            }
        case '{':
            addChar();
            nextToken = LEFT_CBRACE;
            break;
        case '}':
            addChar();
            nextToken = RIGHT_CBRACE;
            break;
        case ';':
            addChar();
            nextToken = SEMICOLON;
            break;
        case '%':
            addChar();
            nextToken = MOD_OP;
            break;
        default:
            addChar();
            nextToken = UNKNOWN;
            break;
    }
    return nextToken;
}

/* printAnswer - Since printing out preprocessor handle is impossible, printAnswer
 * prints out in required format according to token code
 *
 * */
void printAnswer() {
    printf("%s and the next token was ", lexeme);
    switch (nextToken) {
        case 0:
            printf("LETTER\n");
            break;
        case 1:
            printf("DIGIT\n");
            break;
        case 10:
            printf("INT_LIT\n");
            break;
        case 11:
            printf("IDENT\n");
            break;
        case 20:
            printf("ASSIGN_OP\n");
            break;
        case 21:
            printf("ADD_OP\n");
            break;
        case 22:
            printf("SUB_OP\n");
            break;
        case 23:
            printf("MULT_OP\n");
            break;
        case 24:
            printf("DIV_OP\n");
            break;
        case 25:
            printf("LEFT_PAREN\n");
            break;
        case 26:
            printf("RIGHT_PAREN\n");
            break;
        case 27:
            printf("LESSER_OP\n");
            break;
        case 28:
            printf("GREATER_OP\n");
            break;
        case 29:
            printf("EQUAL_OP\n");
            break;
        case 30:
            printf("NEQUAL_OP\n");
            break;
        case 31:
            printf("LEQUAL_OP\n");
            break;
        case 32:
            printf("GEQUAL_OP\n");
            break;
        case 33:
            printf("SEMICOLON\n");
            break;
        case 34:
            printf("MOD_OP\n");
            break;
        case 35:
            printf("LEFT_CBRACE\n");
            break;
        case 36:
            printf("RIGHT_CBRACE\n");
            break;
        case 37:
            printf("KEY_READ\n");
            break;
        case 38:
            printf("KEY_PRINT\n");
            break;
        case 39:
            printf("KEY_WHILE\n");
            break;
        case 40:
            printf("KEY_DO\n");
            break;
        case 99:
            printf("UNKNOWN\n");
            break;
        default:
            printf("wtf\n");
            break;
    }
}